---

- name: "config apt via apt-cacher-ng"
  template:
    src: 01proxy.j2
    dest: /etc/apt/apt.conf.d/01proxy
    owner: "root"
    group: "root"
    mode: 0744
  when: ansible_os_family == "Debian"

- name: "config yum via apt-cacher-ng"
  template:
    src: yum.conf.j2
    dest: /etc/yum.conf
    owner: "root"
    group: "root"
    mode: 0744
  when: ansible_os_family == "RedHat"

- name: "Disble yum-facstmirror plugin"
  lineinfile: dest=/etc/yum/pluginconf.d/fastestmirror.conf state=present regexp='^enabled=' line='enabled=0'
  when: ansible_os_family == "RedHat"