---

- name: "remove apt proxy config before starting - or we are in a deadlock ;)"
  file: path=/etc/apt/apt.conf.d/01proxy state=absent

- name: "install apt pkgs"
  apt: name="{{ item }}" state="installed" update_cache=true
  with_items:
    - curl
    - apt-cacher-ng
  when: docker_mode == False

#- name: "Create apt-cacher-dir on hosting OS"
#  file:
#    state: directory
#    path: /etc/apt-cacher-ng/
#    owner: root
#    group: root
#    mode: 777

#- name: "Generate Vagrant run-time configurations"
#  template:
#    src: "{{ item }}.j2"
#    dest: "/etc/apt-cacher-ng/{{ item }}"
#    owner: "{{ apt_cacher_ng_user }}"
#    group: "{{ apt_cacher_ng_group }}"
#    mode: 755
#  with_items:
#    - centos_mirrors
#    - acng.conf
#  when: apt_mode is defined



- name: "set this fact so the host running cacher is also using the apt-cacher-ng"
  set_fact:
    apt_proxy_host: 127.0.0.1

